### ISSUE TITLE
Generated alg numbers

### ISSUE THREAD

**Issue by adiwastu** [trangium/trangium.github.io#4]
Hi Trangium,

Is it possible to add numbers to generated algs? I'm talking about pointers for when you need to regen some cases (the #24-25 stuff for example). It is easy to manually count when the number of cases is relatively small, but as the algset goes bigger (e.g. >50) it becomes kinda tedious to manually count. What do you think? Thank you!

Best,
adiwastu/hotland

**Comment by trangium** [comment]
This feature exists! If you're generating algs with images, hover over the image to get its case number. If you're generating algs without images, the case numbers are automatically shown.

**Comment by adiwastu** [comment]
Bruh how I never tried to hover! It indeed exists, thanks!
